config/routes.rb
Rails.application.routes.draw do

	resources :books, :movies, :tv_seasons, :comics, :graphic_novels, :users
	resource :sessions, only: [:new, :create, :destroy]

  root 'sessions#new'

end

app/models/book.rb
class Book < ActiveRecord::Base

	# attr_accessible :title
	#
	# validates :title, presence: true, uniqueness: true
	#
	# # It returns the articles whose titles contain one or more words that form the query
	# def self.search(query)
	# 	# where(:title, query) -> This would return an exact match of the query
	# 	where("title like ?", "%#{query}%")
	# end

end

app/models/comic.rb
class Comic < ActiveRecord::Base
end

app/models/graphic_novel.rb
class GraphicNovel < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/tv_season.rb
class TvSeason < ActiveRecord::Base
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
	has_secure_password

	has_many :books
	has_many :movies
	has_many :comics
	has_many :graphic_novels
	has_many :tv_seasons

	validates :name, 		 presence: true, length: { maximum: 20 }
	validates :password, presence: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
	validates_uniqueness_of :email

	def a_method_used_for_validation_purposes
		errors.add(:name,  'cannot be more than 20 characters long')
		errors.add(:email, 'not a valid email address')
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		@books = Book.where(user_id: session['user_id'])
		# 	if params[:search]
		# 		@books = Book.search(params[:search])
		# 	else
		# 		@books = Book.where(user_id: session['user_id'])
		# 	end
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.create(params.require(:book).permit(:title, :author_first, :author_last, :year, :genre, :is_loaned,
																										 :user_id))
		if @book.save
			# UserMailer.new_book(@book).deliver
			redirect_to books_path
		else
			render 'new'
		end
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update_attributes(params.require(:book).permit(:title, :author_first, :author_last, :year, :genre, :is_loaned, :user_id))
			redirect_to books_path
		else
			render 'edit'
		end
	end

	def show
		@book = Book.find(params[:id])
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController

	def index
		@comics = Comic.where(user_id: session['user_id'])
	end

	def new
		@comic = Comic.new
	end

	def create
		@comic = Comic.create(params.require(:comic).permit(:title, :number, :publisher, :comic_box, :is_loaned, :user_id))
		if @comic.save
			redirect_to comics_path
		else
			render 'new'
		end
	end

	def edit
		@comic = Comic.find(params[:id])
	end

	def update
		@comic = Comic.find(params[:id])
		if @comic.update_attributes(params.require(:comic).permit(:title, :number, :publisher, :comic_box, :is_loaned, :user_id))
			redirect_to comics_path
		else
			render 'edit'
		end
	end

	def show
		@comic = Comic.find(params[:id])
	end

	def destroy
		@comic = Comic.find(params[:id])
		@comic.destroy
		redirect_to comics_path
	end

end

app/controllers/graphic_novels_controller.rb
class GraphicNovelsController < ApplicationController

	def index
		@graphic_novels = GraphicNovel.where(user_id: session['user_id'])
	end

	def new
		@graphic_novel = GraphicNovel.new
	end

	def create
		@graphic_novel = GraphicNovel.create(params.require(:graphic_novel).permit(:title, :number, :author, :publisher, :is_loaned, :user_id))
		if @graphic_novel.save
			redirect_to graphic_novels_path
		else
			render 'new'
		end
	end

	def edit
		@graphic_novel = GraphicNovel.find(params[:id])
	end

	def update
		@graphic_novel = GraphicNovel.find(params[:id])
		if @graphic_novel.update_attributes(params.require(:graphic_novel).permit(:title, :number, :author, :publisher, :is_loaned, :user_id))
			redirect_to graphic_novels_path
		else
			render 'edit'
		end
	end

	def show
		@graphic_novel = GraphicNovel.find(params[:id])
	end

	def destroy
		@graphic_novel = GraphicNovel.find(params[:id])
		@graphic_novel.destroy
		redirect_to graphic_novels_path
	end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def index
		@movies = Movie.where(user_id: session['user_id'])
		@base_url   = "http://api.rottentomatoes.com/api/public/v1.0/movies.json?q="
		@page_limit = "&page_limit=10&apikey="
		@api_key    = ENV['RT_API_KEY']
	end

	def new
		@movie = Movie.new
	end

	def create
		@movie = Movie.create(params.require(:movie).permit(:title, :year, :director, :writer, :rotten_tomatoes, :format, :is_loaned, :user_id))
		if @movie.save
			redirect_to movies_path
		else
			render 'new'
		end
	end

	def edit
		@movie = Movie.find(params[:id])
	end

	def update
		@movie = Movie.find(params[:id])
		if @movie.update_attributes(params.require(:movie).permit(:title, :year, :director, :writer, :rotten_tomatoes, :format, :is_loaned, :user_id))
			redirect_to movies_path
		else
			render 'edit'
		end
	end

	def show
		@movie = Movie.find(params[:id])
	end

	def destroy
		@movie = Movie.find(params[:id])
		@movie.destroy
		redirect_to movies_path
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new #the new session form is based on a user
	end

	def create
		#find the user by their email
		user = User.where(email: params[:user][:email]).first
		if user != nil && user.authenticate(params[:user][:password])
			session['user_id'] = user.id.to_s #Session is built-in to Rails; it's like a cookie
			@current_user = User.find(session['user_id'])
			redirect_to user_path(session['user_id'])
		else
			redirect_to new_sessions_path
		end
	end

	def destroy
		session.destroy
		redirect_to new_sessions_path
	end

end

app/controllers/tv_seasons_controller.rb
class TvSeasonsController < ApplicationController

	def index
		@tv_seasons = TvSeason.where(user_id: session['user_id'])
		# Tmdb::Api.key("KEY_HERE")
	end

	def new
		@tv_season = TvSeason.new
	end

	def create
		@tv_season = TvSeason.create(params.require(:tv_season).permit(:title, :season, :year, :show_runner, :network, :format, :is_loaned, :user_id))
		if @tv_season.save
			redirect_to tv_seasons_path
		else
			render 'new'
		end
	end

	def edit
		@tv_season = TvSeason.find(params[:id])
	end

	def update
		@tv_season = TvSeason.find(params[:id])
		if @tv_season.update_attributes(params.require(:tv_season).permit(:title, :season, :year, :show_runner, :network, :format, :is_loaned, :user_id))
			redirect_to tv_seasons_path
		else
			render 'edit'
		end
	end

	def show
		@tv_season = TvSeason.find(params[:id])
	end

	def destroy
		@tv_season = TvSeason.find(params[:id])
		@tv_season.destroy
		redirect_to tv_seasons_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.create(params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar))
		if @user.save
			# UserMailer.welcome(@user).deliver
			redirect_to new_sessions_path
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar))
			redirect_to user_path(session['user_id'])
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/graphic_novels_helper.rb
module GraphicNovelsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tv_seasons_helper.rb
module TvSeasonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading text-capitalize">Update <%= @book.title %></h1></div>
	<div class="col-md-6 text-center"><%= link_to image_tag('cancel.png', class: 'small-circle'), books_path(session['user_id']) %></div>
</div>

<%= form_for @book do |f| %>
	<div class="info-list">
		<%= f.text_field :title,        placeholder: 'Title' %><br>
		<%= f.text_field :author_first, placeholder: 'Author first name' %>
		<%= f.text_field :author_last,  placeholder: 'last name' %><br>
		<%= f.number_field :year,       placeholder: 'Year' %><br><br>

		Loaned Out?: <%= f.check_box :is_loaned %><br><br>

		<%= f.submit 'Update!' %><br>
	</div>
<% end %>

app/views/books/index.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading">Books</h1></div>
	<div class="col-md-6 text-center"><%= link_to image_tag('add.png', class: 'small-circle'), new_book_path %></div>
</div>

<!--<div class="total-things-background"><img src="/assets/logo-blank.png">-->
<!--<div class="total-things"><%#= Book.where(user_id: session['user_id']).count %></div>-->
<!--</div>-->

<div class="index-list">
	<table>
		<thead>
		<tr>
			<th>Title</th>
			<th>Author</th>
			<th>Year</th>
			<th>Loaned Out</th>
			<th>Actions</th>
			<th colspan="5"></th>
		</tr>
		</thead>

		<tbody>
		<% @books.sort_by { |b| b[:author_last].downcase }.each do |book| %>
			<tr>
				<td class="text-capitalize"><%= book.title %></td>
				<td class="text-capitalize"><%= book.author_first %> <%= book.author_last %></td>
				<td class="text-capitalize"><%= book.year %></td>
				<td class="text-capitalize"><%= book.is_loaned %></td>
				<td><%= link_to 'View', book %>
					  <%= link_to 'Delete', book, method: :delete, data: {confirm: "Are you sure?"} %>
					  <%= link_to 'Edit', edit_book_path(book) %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/books/new.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading">Add a book!</h1></div>
	<div class="col-md-6 text-center"><%= link_to image_tag('cancel.png', class: 'small-circle'), books_path(session['user_id']) %></div>
</div>

<%= form_for @book do |f| %>
	<div class="info-list">
		<%= f.collection_select :user_id, User.all, :id, :name, include_blank: 'User' %><br>
		<%= f.text_field :title,        placeholder: 'Title' %><br>
		<%= f.text_field :author_first, placeholder: 'Author first name' %>
		<%= f.text_field :author_last,  placeholder: 'last name' %><br>
		<%= f.number_field :year,       placeholder: 'Year' %><br><br>

		Loaned Out?: <%= f.check_box :is_loaned %><br><br>

		<%= f.submit 'Add this book!' %><br>
	</div>
<% end %>

app/views/books/show.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading text-capitalize"><%= @book.title %></h1></div>
	<div class="col-md-6 text-center">
		<%= link_to image_tag('delete.png', class: 'small-circle'), @book, method: :delete, data: {confirm: "Are you sure?"} %>
		<%= link_to image_tag('edit.png', class: 'small-circle'), edit_book_path(@book) %>
		<%= link_to image_tag('cancel.png', class: 'small-circle'), books_path(session['user_id']) %>
	</div>
</div>

<div class="list-of-stuff">
	<p class="text-capitalize">Author: <%= @book.author_first %> <%= @book.author_last %></p>
	<p class="text-capitalize">Year:   <%= @book.year %></p>
	<p class="text-capitalize">Loaned Out?: <%= @book.is_loaned %></p>
</div>

app/views/comics/edit.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading text-capitalize">Update <%= @comic.title %></h1></div>
	<div class="col-md-6 text-center"><%= link_to image_tag('cancel.png', class: 'small-circle'), comics_path(session['user_id']) %></div>
</div>

<%= form_for @comic do |f| %>
	<div class="info-list">
		<%= f.text_field :title, placeholder: 'Title' %><br>
		<%= f.number_field :number, placeholder: 'Number' %><br>
		<%= f.text_field :publisher, placeholder: 'Publisher' %><br>
		<%= f.text_field :comic_box, placeholder: 'Location' %><br><br>

		Loaned Out?: <%= f.check_box :is_loaned %><br><br>

		<%= f.submit 'Update!' %><br>
	</div>
<% end %>

app/views/comics/index.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading">Comics</h1></div>
	<div class="col-md-6 text-center"><%= link_to image_tag('add.png', class: 'small-circle'), new_comic_path %></div>
</div>

<div class="index-list">
	<table>
		<thead>
		<tr>
			<th>Title</th>
			<th>Number</th>
			<th>Publisher</th>
			<th>Location</th>
			<th>Loaned Out</th>
			<th>Actions</th>
			<th colspan="6"></th>
		</tr>
		</thead>

		<tbody>
		<% @comics.sort_by { |c| c[:title].downcase }.each do |comic| %>
			<tr>
				<td class="text-capitalize"><%= comic.title %></td>
				<td class="text-capitalize year"><%= comic.number %></td>
				<td class="text-capitalize"><%= comic.publisher  %></td>
				<td class="text-capitalize"><%= comic.comic_box %></td>
				<td class="text-capitalize"><%= comic.is_loaned %></td>
				<td><%= link_to 'View', comic %>
					<%= link_to 'Delete', comic, method: :delete, data: {confirm: "Are you sure?"} %>
					<%= link_to 'Edit', edit_comic_path(comic) %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/comics/new.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading">Add a comic!</h1></div>
	<div class="col-md-6 text-center"><%= link_to image_tag('cancel.png', class: 'small-circle'), comics_path(session['user_id']) %></div>
</div>

<%= form_for @comic do |f| %>
	<div class="info-list">
		<%= f.collection_select :user_id, User.all, :id, :name, include_blank: 'User' %><br>
		<%= f.text_field :title,     placeholder: 'Title' %><br>
		<%= f.number_field :number,  placeholder: 'Number' %><br>
		<%= f.text_field :publisher, placeholder: 'Publisher' %><br>
		<%= f.text_field :comic_box, placeholder: 'Location' %><br><br>

		Loaned Out?: <%= f.check_box :is_loaned %><br><br>

		<%= f.submit 'Update!' %><br>
	</div>
<% end %>

app/views/comics/show.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading text-capitalize"><%= @comic.title %></h1></div>
	<div class="col-md-6 text-center">
		<%= link_to image_tag('delete.png', class: 'small-circle'), @comic, method: :delete, data: {confirm: "Are you
		sure?"} %>
		<%= link_to image_tag('edit.png', class: 'small-circle'), edit_comic_path(@comic) %>
		<%= link_to image_tag('cancel.png', class: 'small-circle'), comics_path(session['user_id']) %>
	</div>
</div>

<div class="list-of-stuff">
	<p>Number: <%= @comic.number %></p>
	<p class="text-capitalize">Publisher: <%= @comic.publisher %></p>
	<p class="text-capitalize">Location: <%= @comic.comic_box %></p>
	<p class="text-capitalize">Loaned Out?: <%= @comic.is_loaned %></p>
</div>

app/views/graphic_novels/edit.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading text-capitalize">Update <%= @graphic_novel.title %></h1></div>
	<div class="col-md-6 text-center"><%= link_to image_tag('cancel.png', class: 'small-circle'), graphic_novels_path(session['user_id']) %></div>
</div>

<%= form_for @graphic_novel do |f| %>
	<div class="info-list">
		<%= f.text_field :title,     placeholder: 'Title' %><br>
		<%= f.text_field :author,    placeholder: 'Author' %><br>
		<%= f.number_field :number,  placeholder: 'Number' %><br>
		<%= f.text_field :publisher, placeholder: 'Publisher' %><br><br>

		Loaned Out?: <%= f.check_box :is_loaned %><br><br>

		<%= f.submit 'Update!' %><br>
	</div>
<% end %>

app/views/graphic_novels/index.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading">Graphic Novels</h1></div>
	<div class="col-md-6 text-center"><%= link_to image_tag('add.png', class: 'small-circle'), new_graphic_novel_path %></div>
</div>

<div class="index-list">
	<table>
		<thead>
		<tr>
			<th>Title</th>
			<th>Author</th>
			<th>Number</th>
			<th>Publisher</th>
			<th>Loaned Out</th>
			<th colspan="5"></th>
		</tr>
		</thead>

		<tbody>
		<% @graphic_novels.sort_by { |gn| gn[:title].downcase }.each do |graphic| %>
			<tr>
				<td class="text-capitalize"><%= graphic.title %></td>
				<td class="text-capitalize"><%= graphic.author %></td>
				<td class="text-capitalize year"><%= graphic.number %></td>
				<td class="text-capitalize"><%= graphic.publisher  %></td>
				<td class="text-capitalize"><%= graphic.is_loaned %></td>
				<td><%= link_to 'View', graphic %>
					<%= link_to 'Delete', graphic, method: :delete, data: {confirm: "Are you sure?"} %>
					<%= link_to 'Edit', edit_graphic_novel_path(graphic) %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/graphic_novels/new.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading">Add a graphic novel!</h1></div>
	<div class="col-md-6 text-center"><%= link_to image_tag('cancel.png', class: 'small-circle'), graphic_novels_path(session['user_id'])	%></div>
</div>

<%= form_for @graphic_novel do |f| %>
	<div class="info-list">
		<%= f.collection_select :user_id, User.all, :id, :name, include_blank: 'User' %><br>
		<%= f.text_field :title,     placeholder: 'Title' %><br>
		<%= f.text_field :author,    placeholder: 'Author' %><br>
		<%= f.number_field :number,  placeholder: 'Number' %><br>
		<%= f.text_field :publisher, placeholder: 'Publisher' %><br><br>

		Loaned Out?: <%= f.check_box :is_loaned %><br><br>

		<%= f.submit 'Update!' %><br>
	</div>
<% end %>

app/views/graphic_novels/show.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading text-capitalize"><%= @graphic_novel.title %></h1></div>
	<div class="col-md-6 text-center">
		<%= link_to image_tag('delete.png', class: 'small-circle'), @graphic_novel, method: :delete, data: {confirm: "Are you
		sure?"} %>
		<%= link_to image_tag('edit.png', class: 'small-circle'), edit_graphic_novel_path(@graphic_novel) %>
		<%= link_to image_tag('cancel.png', class: 'small-circle'), graphic_novels_path(session['user_id']) %>
	</div>
</div>

<div class="list-of-stuff">
	<p class="text-capitalize">Author: <%= @graphic_novel.author %></p>
	<p class="text-capitalize">Number: <%= @graphic_novel.number %></p>
	<p class="text-capitalize">Publisher: <%= @graphic_novel.publisher %></p>
	<p class="text-capitalize">Loaned Out?: <%= @graphic_novel.is_loaned %></p>
</div>

app/views/movies/edit.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading text-capitalize">Update <%= @movie.title %></h1></div>
	<div class="col-md-6 text-center"><%= link_to image_tag('cancel.png', class: 'small-circle'), movies_path(session['user_id']) %></div>
</div>

<%= form_for @movie do |f| %>
	<div class="info-list">
		<%= f.text_field :title,    placeholder: 'Title' %><br>
		<%= f.number_field :year,   placeholder: 'Year' %><br>
		<%= f.text_field :director, placeholder: 'Director' %><br>
		<%= f.text_field :writer,   placeholder: 'Writer' %><br><br>
		<%= f.radio_button :format, 'DVD' %><%= f.label :format, 'DVD', value: 'dvd' %>
		<%= f.radio_button :format, 'Blu-Ray' %><%= f.label :format, 'Blu-Ray', value: 'bluray' %><br><br>

		Loaned Out?: <%= f.check_box :is_loaned %><br><br>

		<%= f.submit 'Add this movie!' %><br>
	</div>
<% end %>

app/views/tv_seasons/index.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading">TV Seasons</h1></div>
	<div class="col-md-6 text-center"><%= link_to image_tag('add.png', class: 'small-circle'), new_tv_season_path %></div>
</div>

<div class="index-list">
	<table>
		<thead>
		<tr>
			<th>Title</th>
			<th>Season</th>
			<th>Year</th>
			<th>Show Runner</th>
			<th>Format</th>
			<th>Loaned Out</th>
			<th>Actions</th>
			<th colspan="8"></th>
		</tr>
		</thead>

		<tbody>
		<% @tv_seasons.sort_by { |t| t[:title].downcase }.each do |tv| %>
			<tr>
				<td class="text-capitalize">     <%= tv.title %></td>
				<td class="text-capitalize">     <%= tv.season %></td>
				<td class="text-capitalize">     <%= tv.year %></td>
				<td class="text-capitalize">     <%= tv.show_runner %></td>
				<td class="text-capitalize">     <%= tv.format %></td>
				<td class="text-capitalize">     <%= tv.is_loaned %></td>
				<td><%= link_to 'View', tv %>
					  <%= link_to 'Delete', tv, method: :delete, data: {confirm: "Are you sure?"} %>
					  <%= link_to 'Edit', edit_tv_season_path(tv) %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/tv_seasons/show.html.erb
<%= render 'users/nav' %>

<div class="row">
	<div class="col-md-6 text-center"><h1 class="heading text-capitalize"><%= @tv_season.title %></h1></div>
	<div class="col-md-6 text-center">
		<%= link_to image_tag('delete.png', class: 'small-circle'), @tv_season, method: :delete, data: {confirm: "Are you sure?"} %>
		<%= link_to image_tag('edit.png', class: 'small-circle'), edit_tv_season_path(@tv_season) %>
		<%= link_to image_tag('cancel.png', class: 'small-circle'), tv_seasons_path(session['user_id']) %>
	</div>
</div>

<div class="list-of-stuff">
	<p class="text-capitalize">Season:      <%= @tv_season.season %></p>
	<p class="text-capitalize">Year:        <%= @tv_season.year %></p>
	<p class="text-capitalize">Show Runner: <%= @tv_season.show_runner %></p>
	<!--<p class="text-capitalize">Network:     <%#= @tv_season.network %></p>-->
	<p class="text-capitalize">Format:      <%= @tv_season.format %></p>
	<p class="text-capitalize">Loaned Out?: <%= @tv_season.is_loaned %></p>
</div>

app/views/users/_nav.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">
				<%= link_to image_tag('logo.png', class: 'logo'), user_path(session['user_id']) %>
			</a>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
						My Stashes <span class="caret"></span>
					</a>
					<ul class="dropdown-menu" role="menu">
						<li><%= link_to image_tag('books.png', class: 'dropdown-logo'),   books_path(session['user_id']) %></li>
						<li><%= link_to image_tag('comics.png', class: 'dropdown-logo'),  comics_path(session['user_id']) %></li>
						<li><%= link_to image_tag('graphic.png', class: 'dropdown-logo'), graphic_novels_path(session['user_id']) %></li>
						<li><%= link_to image_tag('movies.png', class: 'dropdown-logo'),  movies_path(session['user_id']) %></li>
						<li><%= link_to image_tag('tv.png', class: 'dropdown-logo'),      tv_seasons_path(session['user_id']) %></li>
					</ul>
				</li>
			</ul>

			<!--<form class="navbar-form navbar-left" role="search">-->
			<!--<div class="form-group">-->
			<!--<input type="text" class="form-control" placeholder="Search">-->
			<!--</div>-->
			<!--<button type="submit" class="btn btn-default">Submit</button>-->
			<!--</form>-->
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Edit profile', edit_user_path(session['user_id']) %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Log out', sessions_path, method: :delete %></li>
			</ul>
		</div>
	</div>
</nav>